<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuizQuestionSeeder extends Seeder
{
    public function run(): void
    {
        $quizQuestions = [
            [
                'id' => 1,
                'quiz_id' => 1,
                'type' => 'multiple_choice',
                'text' => 'What is the correct meaning of "Hello"?',
                'image_path' => null,
                'points' => 10,
                'explanation' => 'Hello is a common greeting in English.',
                'options' => json_encode(["Goodbye", "Hello", "Thank you", "Sorry"]),
                'correct_answers' => json_encode([2]),
                'order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'quiz_id' => 1,
                'type' => 'multiple_choice',
                'text' => 'Which word means "a place where people live"?',
                'image_path' => null,
                'points' => 10,
                'explanation' => 'A house is a building where people live.',
                'options' => json_encode(["Car", "Tree", "House", "Book"]),
                'correct_answers' => json_encode([3]),
                'order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'quiz_id' => 1,
                'type' => 'true_false',
                'text' => 'The capital of the United Kingdom is London.',
                'image_path' => null,
                'points' => 5,
                'explanation' => 'London is indeed the capital of the United Kingdom.',
                'options' => json_encode(["False", "True"]),
                'correct_answers' => json_encode([2]),
                'order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'quiz_id' => 2,
                'type' => 'multiple_choice',
                'text' => 'What is the Spanish word for "hello"?',
                'image_path' => null,
                'points' => 10,
                'explanation' => '"Hola" means hello in Spanish.',
                'options' => json_encode(["Adiós", "Gracias", "Hola", "Por favor"]),
                'correct_answers' => json_encode([3]),
                'order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'quiz_id' => 2,
                'type' => 'multiple_choice',
                'text' => 'Which is the correct conjugation of "hablar" (to speak) for "yo" (I)?',
                'image_path' => null,
                'points' => 15,
                'explanation' => 'The correct conjugation of "hablar" for "yo" is "hablo".',
                'options' => json_encode(["hablas", "habla", "hablamos", "hablo"]),
                'correct_answers' => json_encode([4]),
                'order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'quiz_id' => 3,
                'type' => 'multiple_choice',
                'text' => 'What is the French word for "thank you"?',
                'image_path' => null,
                'points' => 10,
                'explanation' => '"Merci" means thank you in French.',
                'options' => json_encode(["Bonjour", "Au revoir", "Merci", "S'il vous plaît"]),
                'correct_answers' => json_encode([3]),
                'order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'quiz_id' => 3,
                'type' => 'multiple_select',
                'text' => 'Which of the following are French colors?',
                'image_path' => null,
                'points' => 15,
                'explanation' => 'Rouge (red), Bleu (blue), and Vert (green) are French colors.',
                'options' => json_encode(["Rouge", "Bleu", "Carro", "Vert"]),
                'correct_answers' => json_encode([1, 2, 4]),
                'order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'quiz_id' => 4,
                'type' => 'multiple_choice',
                'text' => 'What is the German word for "yes"?',
                'image_path' => null,
                'points' => 10,
                'explanation' => '"Ja" means yes in German.',
                'options' => json_encode(["Nein", "Ja", "Bitte", "Danke"]),
                'correct_answers' => json_encode([2]),
                'order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'quiz_id' => 4,
                'type' => 'true_false',
                'text' => 'The German word for water is "Wasser".',
                'image_path' => null,
                'points' => 5,
                'explanation' => '"Wasser" is indeed the German word for water.',
                'options' => json_encode(["False", "True"]),
                'correct_answers' => json_encode([2]),
                'order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'quiz_id' => 5,
                'type' => 'multiple_choice',
                'text' => 'Which of the following is a correct usage of the past perfect tense?',
                'image_path' => null,
                'points' => 20,
                'explanation' => 'The past perfect tense uses "had" + past participle.',
                'options' => json_encode(["I am walking", "I walked", "I had walked", "I will walk"]),
                'correct_answers' => json_encode([3]),
                'order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('quiz_questions')->insert($quizQuestions);
    }
}
